### ISSUE TITLE
jdk

### ISSUE THREAD

**Issue by zkh26** [ziwenxie/leafer#4]
项目用的jdk和maven的版本是不是发出来下

**Comment by ziwenxie** [comment]
maven3.x + jdk1.8

2017-06-23 10:49 GMT+08:00 zkh26 <notifications@github.com>:

**Comment by zkh26** [comment]
我刚看springboot的时候就调了好长时间的环境，现在又得弄一次，我试了，那样没起来

**Comment by ziwenxie** [comment]
贴下具体的报错信息，请确保数据库已经正常配置。

**Comment by zkh26** [comment]
ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalArgumentException: Could not resolve placeholder 'HOME' in value "${HOME}/leafer-sfl4j.log"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
	at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:227)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:83)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:61)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:530)
	at org.springframework.boot.logging.LogFile.get(LogFile.java:116)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:271)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:212)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at org.ziwenxie.leafer.Application.main(Application.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.370 s
[INFO] Finished at: 2017-06-23T12:01:05+08:00
[INFO] Final Memory: 21M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.3.RELEASE:run (default-cli) on project article: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by ziwenxie** [comment]
你的运行环境应该是windows，打开`src/main/resources/application.properties`替换下面的`${HOME}`为windows下的相关路径应该就行了。

```xml
# define logging file
logging.file=${HOME}/leafer-sfl4j.log
```

**Comment by zkh26** [comment]
![image](https://user-images.githubusercontent.com/25739709/27466440-42583f32-580d-11e7-907d-0a4fb47ba96a.png)
厉害了，这个图片是登录页面上没有显示图片正常吗，

**Comment by ziwenxie** [comment]
@zkh26 

图片可能被防火墙屏蔽了，先试一试代理看看。

**Comment by zkh26** [comment]
我防火墙没开，还有一点是
![image](https://user-images.githubusercontent.com/25739709/27466485-b037ab78-580d-11e7-87f5-2e5d0414c950.png)
让我移除override,什么情况？还有试试代理是什么？
我午睡了，1点多再回复你

**Comment by ziwenxie** [comment]
1. 代理就是翻墙。

2. 之所以通过命令行能正常运行是因为maven使用的jdk1.8，[设置一下你的eclipse环境](https://stackoverflow.com/questions/8697513/why-do-i-get-must-override-a-superclass-method-with-override)就行了。

**Comment by zkh26** [comment]
我把项目删掉重新导入的，override的那个错误没了，但是这个好像也是和jdk版本有关系

**Comment by zkh26** [comment]
The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
想截图的但是上传不上去了

**Comment by zkh26** [comment]
![Uploading QQ截图20170623155706.png…]()
